import { CheckCircle2, FileText, ShieldCheck } from "lucide-react";
import { mapFactors, type Translation } from "./data";
export function LenderView({t,data,user}:{t:Translation;data:any;user:any}) {
  const factors = mapFactors(data?.factors);
  const total = factors.reduce((a:number,f:any)=>a+f.max,0);
  const vp = total ? Math.round(100*factors.filter((f:any)=>f.confidence==="verified").reduce((a:number,f:any)=>a+f.max,0)/total) : 0;
  return <main className="min-h-screen bg-surface-subtle pb-12"><div className="border-b border-verified-border bg-verified-soft"><div className="mx-auto flex max-w-5xl items-center gap-3 px-4 py-4 md:px-6"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-verified text-primary-foreground"><ShieldCheck className="size-6"/></span><div><p className="font-bold text-verified">{t.authentic}</p><p className="text-sm text-foreground">{t.unchanged}</p></div></div></div>
  <div className="mx-auto max-w-5xl px-4 py-6 md:px-6 md:py-10"><div className="mb-6 flex items-center gap-3"><span className="grid size-12 place-items-center rounded-md bg-primary text-primary-foreground"><FileText/></span><div><p className="text-sm font-semibold text-primary">Credit Passport</p><h1 className="text-2xl font-bold">{user.business}</h1></div></div>
  <section className="grid overflow-hidden rounded-lg border border-border bg-card shadow-card md:grid-cols-3"><div className="p-5"><p className="text-xs font-bold uppercase text-muted-foreground">{t.businessId}</p><p className="mt-2 font-bold">{user.name}</p><p className="mt-1 text-sm text-muted-foreground">{t.alias}: {user.business}</p></div><div className="border-y border-border p-5 md:border-x md:border-y-0"><p className="text-xs font-bold uppercase text-muted-foreground">{t.overallScore}</p><p className="mt-1 text-4xl font-bold text-primary">{data?.score ?? 0}<span className="text-lg text-muted-foreground">/100</span></p><p className="text-sm font-semibold text-verified">Good credit health</p></div><div className="p-5"><p className="text-xs font-bold uppercase text-muted-foreground">{t.confidence}</p><div className="mt-3 flex h-3 overflow-hidden rounded-full"><span className="bg-verified" style={{width:vp+"%"}}/><span className="bg-reported" style={{width:(100-vp)+"%"}}/></div><div className="mt-2 flex justify-between text-xs font-semibold"><span>{vp}% verified</span><span>{100-vp}% self-reported</span></div></div></section>
  <section className="mt-6 overflow-hidden rounded-lg border border-border bg-card shadow-card"><div className="border-b border-border p-5"><h2 className="text-lg font-bold">{t.factorSummary}</h2></div><div className="hidden grid-cols-[1fr_2fr_auto_auto] gap-4 border-b border-border bg-muted px-5 py-3 text-xs font-bold uppercase text-muted-foreground md:grid"><span>{t.factor}</span><span>{t.evidence}</span><span>Score</span><span>{t.source}</span></div>{factors.map((item:any)=><div key={item.key} className="grid gap-2 border-b border-border p-5 last:border-0 md:grid-cols-[1fr_2fr_auto_auto] md:items-center md:gap-4"><p className="font-bold">{t[item.key as keyof typeof t]}</p><p className="text-sm text-muted-foreground">{item.note}</p><p className="font-bold text-primary">{item.score}/{item.max}</p><span className={item.confidence==="verified"?"badge-verified":"badge-reported"}>{item.confidence==="verified"?<CheckCircle2 className="size-3"/>:null}{item.confidence==="verified"?t.verified:t.reported}</span></div>)}</section>
  <section className="mt-6 rounded-lg border border-border bg-muted p-5"><h2 className="font-bold">{t.limitations}</h2><ol className="mt-4 space-y-3">{[t.limitation1,t.limitation2,t.limitation3].map((text,i)=><li key={text} className="grid grid-cols-[auto_1fr] gap-3 text-sm leading-6 text-muted-foreground"><span className="grid size-6 place-items-center rounded-full bg-card text-xs font-bold text-foreground">{i+1}</span>{text}</li>)}</ol></section>
  </div></main> }
