import { useState } from "react";
import * as Switch from "@radix-ui/react-switch";
import * as AlertDialog from "@radix-ui/react-alert-dialog";
import { BarChart3, Check, CheckCircle2, Clock3, Copy, Gauge, Link2, LockKeyhole, MessageCircle, ShieldCheck, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { mockShares, type ShareRecord, type Translation } from "./data";

export function ConsentForm({ t, onBack, onCreateLink }: { t: Translation; onBack: () => void; onCreateLink: (recipient: string, duration: string, sections: ShareRecord["sections"]) => void }) {
  const [recipient, setRecipient] = useState("Bank of Maharashtra, Pune branch");
  const [duration, setDuration] = useState("7 days");
  const [sections, setSections] = useState({ score: true, charts: true, confidence: true });
  const rows = [
    ["score", Gauge, t.scoreBreakdown, t.scoreDesc], ["charts", BarChart3, t.chartsTrends, t.chartsDesc], ["confidence", ShieldCheck, t.confidenceLabels, t.confidenceDesc],
  ] as const;
  return <FlowShell onBack={onBack}><div className="mx-auto max-w-2xl"><div className="mb-7"><p className="text-sm font-semibold text-primary">Step 1 of 3</p><h1 className="mt-1 text-3xl font-bold text-foreground">{t.shareTitle}</h1><p className="mt-2 text-muted-foreground">{t.shareSubtitle}</p></div>
    <div className="space-y-5">
      <section className="rounded-lg border border-border bg-card p-5 shadow-card"><label htmlFor="recipient" className="text-sm font-bold text-foreground">{t.whoFor}</label><input id="recipient" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder={t.whoPlaceholder} className="mt-2 min-h-12 w-full rounded-md border border-input bg-background px-4 text-foreground outline-hidden placeholder:text-muted-foreground focus:ring-3 focus:ring-ring" /></section>
      <section className="rounded-lg border border-border bg-card p-5 shadow-card"><h2 className="mb-2 text-base font-bold">{t.whatSee}</h2><div className="divide-y divide-border">{rows.map(([key,Icon,title,desc])=><div key={key} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 py-4"><span className="grid size-11 place-items-center rounded-md bg-primary-soft text-primary"><Icon className="size-5" /></span><div className="min-w-0"><p className="text-sm font-bold text-foreground">{title}</p><p className="text-xs leading-5 text-muted-foreground">{desc}</p></div><Switch.Root aria-label={title} checked={sections[key]} onCheckedChange={(checked)=>setSections({...sections,[key]:checked})} className="relative h-7 w-12 shrink-0 rounded-full bg-input transition-colors data-[state=checked]:bg-primary"><Switch.Thumb className="block size-5 translate-x-1 rounded-full bg-card shadow-sm transition-transform data-[state=checked]:translate-x-6" /></Switch.Root></div>)}</div></section>
      <section className="rounded-lg border border-border bg-card p-5 shadow-card"><h2 className="mb-3 text-base font-bold">{t.howLong}</h2><div className="grid grid-cols-3 gap-2">{[[t.hours24,"24 hours"],[t.days7,"7 days"],[t.days30,"30 days"]].map(([label,value])=><button key={value} type="button" onClick={()=>setDuration(value)} className={`min-h-14 rounded-md border px-2 text-sm font-bold transition-colors focus-visible:outline-hidden focus-visible:ring-3 focus-visible:ring-ring ${duration===value?"border-primary bg-primary-soft text-primary":"border-border bg-background text-foreground"}`}>{label}{value==="7 days" && <span className="mt-0.5 block text-[10px] font-semibold text-muted-foreground">{t.default}</span>}</button>)}</div></section>
      <div className="flex gap-3 rounded-lg border border-border bg-muted p-4 text-sm text-muted-foreground"><LockKeyhole className="size-5 shrink-0 text-primary"/><p className="leading-6">{t.privacy}</p></div>
      <Button className="w-full" disabled={!recipient.trim() || !Object.values(sections).some(Boolean)} onClick={()=>onCreateLink(recipient,duration,sections)}><Link2 className="size-5"/>{t.createLink}</Button>
    </div>
  </div></FlowShell>;
}

export function LinkCreated({ t, share, onDone, onViewLinks, onCopyLink }: { t: Translation; share: ShareRecord; onDone: () => void; onViewLinks: () => void; onCopyLink: (link: string) => void }) {
  const [copied,setCopied]=useState(false);
  const copy=()=>{ onCopyLink(share.link); setCopied(true); setTimeout(()=>setCopied(false),1500); };
  return <FlowShell onBack={onDone}><div className="mx-auto max-w-xl text-center"><div className="mx-auto grid size-20 place-items-center rounded-full bg-verified-soft text-verified"><CheckCircle2 className="size-11"/></div><p className="mt-5 text-sm font-semibold text-primary">Step 2 of 3</p><h1 className="mt-1 text-3xl font-bold">{t.linkReady}</h1><p className="mt-2 text-muted-foreground">{t.linkReadyDesc}</p>
    <div className="mt-7 rounded-lg border border-border bg-card p-5 text-left shadow-card"><label className="text-xs font-bold uppercase text-muted-foreground">Share link</label><div className="mt-2 flex min-h-14 items-center gap-2 rounded-md border border-input bg-background px-3"><Link2 className="size-4 shrink-0 text-primary"/><input readOnly aria-label="Generated share link" value={share.link} className="min-w-0 grow bg-transparent text-sm text-foreground outline-hidden"/></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Button variant="secondary" onClick={copy}>{copied?<Check className="size-5"/>:<Copy className="size-5"/>}{copied?t.copied:t.copyLink}</Button><Button variant="whatsapp" onClick={()=>window.open(`https://wa.me/?text=${encodeURIComponent(share.link)}`,"_blank","noopener,noreferrer")}><MessageCircle className="size-5"/>{t.whatsapp}</Button></div></div>
    <div className="mt-4 rounded-lg border border-border bg-card p-5 text-left"><dl className="space-y-4"><div><dt className="text-xs font-semibold uppercase text-muted-foreground">{t.sharedWith}</dt><dd className="mt-1 font-bold text-foreground">{share.lenderLabel}</dd></div><div><dt className="text-xs font-semibold uppercase text-muted-foreground">{t.included}</dt><dd className="mt-2 flex flex-wrap gap-2">{sectionBadges(share,t)}</dd></div><div className="flex items-center gap-2 border-t border-border pt-4 text-sm font-semibold text-foreground"><Clock3 className="size-4 text-terracotta"/>{t.expires}</div></dl></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2"><Button variant="secondary" onClick={onDone}>{t.done}</Button><Button onClick={onViewLinks}>{t.viewLinks}</Button></div>
  </div></FlowShell>;
}

export function SharedLinksList({ t, shares, onBack, onSharePassport, onRevokeShare }: { t: Translation; shares: ShareRecord[]; onBack:()=>void; onSharePassport:()=>void; onRevokeShare:(id:string)=>void }) {
  const [revoke,setRevoke]=useState<ShareRecord|null>(null);
  return <FlowShell onBack={onBack}><div className="mx-auto max-w-3xl"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0"><p className="text-sm font-semibold text-primary">Step 3 of 3</p><h1 className="mt-1 truncate text-3xl font-bold">{t.myLinks}</h1><p className="mt-2 text-muted-foreground">{t.manageLinks}</p></div><Button size="sm" onClick={onSharePassport}><Link2 className="size-4"/><span className="hidden sm:inline">{t.sharePassport}</span></Button></div>
    {shares.length===0?<div className="mt-8 rounded-lg border border-dashed border-border bg-card p-10 text-center"><Link2 className="mx-auto size-10 text-muted-foreground"/><p className="mt-4 font-semibold">{t.empty}</p><Button className="mt-5" onClick={onSharePassport}>{t.sharePassport}</Button></div>:<div className="mt-7 space-y-4">{shares.map(share=><article key={share.id} className="rounded-lg border border-border bg-card p-5 shadow-card"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div className="min-w-0"><h2 className="truncate font-bold text-foreground">{share.lenderLabel}</h2><div className="mt-2 flex flex-wrap gap-2">{sectionBadges(share,t)}</div></div><Status status={share.status} t={t}/></div><div className="mt-4 grid gap-2 border-t border-border pt-4 text-sm text-muted-foreground sm:grid-cols-2"><p className="flex items-center gap-2"><Clock3 className="size-4"/>Expires {new Date(share.expiresAt).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</p><p>{t.opened.replace("{count}",String(share.openCount)).replace("{time}",share.lastOpenedAt)}</p></div>{share.status==="active"&&<Button variant="danger" className="mt-4 w-full sm:w-auto" onClick={()=>setRevoke(share)}><Trash2 className="size-4"/>{t.revoke}</Button>}</article>)}</div>}
  </div>
  <AlertDialog.Root open={Boolean(revoke)} onOpenChange={(open)=>!open&&setRevoke(null)}><AlertDialog.Portal><AlertDialog.Overlay className="fixed inset-0 z-50 bg-overlay"/><AlertDialog.Content className="fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-md -translate-x-1/2 -translate-y-1/2 rounded-lg bg-card p-6 shadow-modal"><AlertDialog.Title className="text-xl font-bold">{t.stopSharing}</AlertDialog.Title><AlertDialog.Description className="mt-2 leading-6 text-muted-foreground">{t.stopMessage.replace("{name}",revoke?.lenderLabel??"")}</AlertDialog.Description><div className="mt-6 grid grid-cols-2 gap-3"><AlertDialog.Cancel asChild><Button variant="secondary">{t.cancel}</Button></AlertDialog.Cancel><AlertDialog.Action asChild><Button variant="danger" onClick={()=>{if(revoke)onRevokeShare(revoke.id);setRevoke(null)}}>{t.confirmRevoke}</Button></AlertDialog.Action></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>
  </FlowShell>;
}

function FlowShell({children,onBack}:{children:React.ReactNode;onBack:()=>void}) { return <main className="min-h-[calc(100vh-73px)] bg-surface-subtle px-4 py-6 md:px-6 md:py-10"><div className="mx-auto mb-4 max-w-3xl"><Button variant="ghost" size="sm" onClick={onBack}><X className="size-4"/>Close</Button></div>{children}</main> }
function sectionBadges(s:ShareRecord,t:Translation){return <>{s.sections.score&&<span className="tag">{t.scoreBreakdown}</span>}{s.sections.charts&&<span className="tag">{t.chartsTrends}</span>}{s.sections.confidence&&<span className="tag">{t.confidenceLabels}</span>}</>}
function Status({status,t}:{status:ShareRecord["status"];t:Translation}){return <span className={`status-${status}`}>{status==="active"?t.active:status==="expired"?t.expired:t.revoked}</span>}
